# This is a basic workflow to help you get started with Actions

name: Build push events

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  pull_request:
  push:
    paths-ignore:
    - "README.md"
    branches:
      - master
      - develop
      - releases/*

jobs:
  build:
    name: ${{ matrix.config.name }}
    
    runs-on: ${{ matrix.config.os }}
    
    defaults:
      run:
        shell: bash
        
    strategy:
      fail-fast: false
      matrix:
        config:

          - os: windows-latest
            name: 'Windows 64'
            fpcup-url: 'https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/1.8.2g/fpclazup-x86_64-win64.exe'
            fpcup-opt: ''
            fpc-url: 'https://svn.freepascal.org/svn/fpc/tags/release_3_2_0'
            laz-url: 'https://svn.freepascal.org/svn/lazarus/tags/lazarus_2_0_10/'
            laz-dir: 'fpcLaz'
            lazbuild: 'fpcLaz/lazarus/lazbuild.exe'
            build-mode: 'Default'
            build-widgetset: 'win32'
            build-os: 'win64'

          - os: ubuntu-latest
            name: 'Linux 64 GTK2'
            fpcup-url: 'https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/1.8.2g/fpclazup-x86_64-linux'
            fpcup-opt: ''
            fpc-url: 'https://svn.freepascal.org/svn/fpc/tags/release_3_2_0'
            laz-url: 'https://svn.freepascal.org/svn/lazarus/tags/lazarus_2_0_10/'
            laz-dir: 'fpcLaz'
            lazbuild: 'fpcLaz/lazarus/lazbuild'
            build-mode: 'Default'
            build-widgetset: 'gtk2'
            build-os: 'linux'
          
          - os: ubuntu-20.04
            name: 'Linux 64 QT5'
            fpcup-url: 'https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/1.8.2g/fpclazup-x86_64-linux'
            fpcup-opt: ''
            fpc-url: 'https://svn.freepascal.org/svn/fpc/tags/release_3_2_0'
            laz-url: 'https://svn.freepascal.org/svn/lazarus/tags/lazarus_2_0_10/'
            laz-dir: 'fpcLaz'
            lazbuild: 'fpcLaz/lazarus/lazbuild'
            build-mode: 'Default'
            build-widgetset: 'qt5'
            build-os: 'linux'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: true
        
    - name: Install Dependencies (Ubuntu)
      if: matrix.config.os == 'ubuntu-latest' || matrix.config.os == 'ubuntu-20.04'
      run: |
        sudo apt-get update
        sudo apt-get -m -y install libgtk2.0-dev libpango1.0-dev libffi-dev libxtst-dev xvfb
        Xvfb :1 &
        
    - name: Install Dependencies (Ubuntu - only QT5)
      if: (matrix.config.os == 'ubuntu-latest' || matrix.config.os == 'ubuntu-20.04') && matrix.config.build-widgetset == 'qt5'
      run: |
        sudo apt-get -m -y install libqt5pas-dev libqt5pas1 qt5-qmake qtbase5-dev qt5-default libqt5x11extras5-dev libxcb-keysyms1-dev

    - name: Generate Cache Hash
      run: echo "${{ matrix.config.fpcup-url }}${{ matrix.config.fpcup-opt }}${{ matrix.config.fpc-url }}${{ matrix.config.laz-url }}${{ matrix.config.name }}" > .cache

    - name: Cache
      id: cache
      uses: actions/cache@v2.1.3
      env:
        cache-name: cache-laz-v0.2
      with:
        path: ${{ matrix.config.laz-dir }}
        key: ${{ runner.os }}-${{ hashFiles('.cache') }}      

    - name: Install Lazarus
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        curl --retry 5 -L -o fpcup ${{ matrix.config.fpcup-url }}
        chmod +x fpcup
        mkdir ${{ matrix.config.laz-dir }}
        ./fpcup --installdir=${{ matrix.config.laz-dir }} --fpcURL=${{ matrix.config.fpc-url }} --lazURL=${{ matrix.config.laz-url }} ${{ matrix.config.fpcup-opt }} --only=docker --noconfirm --verbose

    - name: Validate Cache
      if: steps.cache.outputs.cache-hit == 'true'
      run: ${{ matrix.config.lazbuild }} --version && echo "::set-output name=success::true" || echo "::set-output name=success::false"

    - name: Build Corona Application (${{ matrix.config.build-mode }})
      run: ${{ matrix.config.lazbuild }} "${{ github.workspace }}/source/corona.lpi" --no-write-project --build-mode="${{ matrix.config.build-mode }}" --widgetset=${{ matrix.config.build-widgetset }} --operating-system=${{ matrix.config.build-os }}

    - name: Upload the Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: Corona Application ${{ matrix.config.build-mode }} build - ${{ matrix.config.build-widgetset }}
        path: |
          ${{ github.workspace}}/corona*
